version: '3.8'
name: tqs
services:
  shop-database:
    image: mysql:5.7
    restart: on-failure 
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${SHOP_DB_NAME}
      MYSQL_USER: ${SHOP_DB_USER}
      MYSQL_PASSWORD: ${SHOP_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${SHOP_DB_ROOT_PASSWORD}
    ports:
      - "${SHOP_DB_PORT}:${SHOP_DB_DOCKER_PORT}"
    volumes:
      - db_shop:/var/lib/mysql

  roadrunner-database:
    image: mysql:5.7
    restart: on-failure 
    env_file:
      - .env
    environment:
        MYSQL_DATABASE: ${RR_DB_NAME}
        MYSQL_USER: ${RR_DB_USER}
        MYSQL_PASSWORD: ${RR_DB_PASSWORD}
        MYSQL_ROOT_PASSWORD: ${RR_DB_ROOT_PASSWORD}
    ports:
        - "${RR_DB_PORT}:${RR_DB_DOCKER_PORT}"
    volumes:
      - db_rr:/var/lib/mysql

  shop-backend:
    depends_on:
      - shop-database
    build:
      context: ./shop-backend
      dockerfile: Dockerfile
    restart: on-failure
    env_file:
      - .env
    ports:
      - "${SHOP_SB_PORT}:${SHOP_SB_DOCKER_PORT}"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://shop-database:${RR_DB_DOCKER_PORT}/${SHOP_DB_NAME}?useSSL=false",
        "spring.datasource.username" : "$SHOP_DB_USER",
        "spring.datasource.password" : "$SHOP_DB_PASSWORD",
        "spring.jpa.hibernate.ddl-auto" : "update"
        }'

  shop-frontend:
    build:
      context: ./shop-frontend
      dockerfile: Dockerfile
    restart: on-failure
    env_file:
      - .env
    ports:
      - "${SHOP_FE_PORT}:${SHOP_FE_DOCKER_PORT}"
    environment:
      VITE_API_URL: 'http://localhost:${SHOP_SB_PORT}'

  roadrunner-backend:
    depends_on:
      - roadrunner-database
    build:
        context: ./roadrunner-backend
        dockerfile: Dockerfile
    restart: on-failure
    env_file:
      - .env

    ports:
        - "${RR_SB_PORT}:${RR_SB_DOCKER_PORT}"
    environment:
      SPRING_APPLICATION_JSON: '{
              "spring.datasource.url"  : "jdbc:mysql://roadrunner-database:${RR_DB_DOCKER_PORT}/${RR_DB_NAME}?useSSL=false",
              "spring.datasource.username" : "$RR_DB_USER",
              "spring.datasource.password" : "$RR_DB_PASSWORD",
              "spring.jpa.hibernate.ddl-auto" : "update"
              }'
volumes:
  db_shop:
  db_rr:
